### PR TITLE
Compensation (built on the temp branch)

### PR DESCRIPTION
**Pull request by mrietveld**
I've added documentation to all of the commits. Please see the commit messages. 

At the moment, simple compensation works: that is to say, the simple use case involving a boundary event handler and an associated compensation activity. 

I'm almost done with compensation event sub processes, except that they basically rely on nested event sub processes working, which isn't the case. I've added a test to test this. 

The problem for nested event sub processes seems to be that registering the (external) event listeners doesn't work/isn't happening, because it doesn't recursively search through the nodes, the way the rest of the logic involving the event sub processes does (NodeContainerImpl.getInnerNode(), for example). 

I'm pretty sure that CompositeNodeInstance.registerExternalEventNodeListeners is what needs to be modified so that it's recursive.

### CODE REVIEW

**Comment by mrietveld** [comment]
So, currently two tests fail: 

org.jbpm.bpmn2.IntermediateEventTest.testEventSubprocessSignalNested
org.jbpm.bpmn2.CompensationTest.compensationViaEventSubProcess

**Comment by mrietveld** [comment]
By the way, I realized that we need to "disallow" compensation event subprocesses for the time being, due to the following reasons: 
1. Compensation event subprocesses (CESP, for short) may only fire when the parent process has completed. 
2. For this reason, CESP's are only allowed within other subprocesses. (Because of 1., it doesn't make sense to have a _non-nested_ CESP: it would only get called once the process had finished -- but then you can't call the CESP because.. the process is finished.)
3. The logic for checking if the parent subprocess has completed isn't complicated, but then it also needs to be added. 

The easiest way to disallow CESP's is to throw an exception in the StartEventHandler (l.170, in the "compensationEventDefinition" clause).

**Comment by mswiderski** [comment]
Marco, wouldn't that work fine as event subprocess is invoked by the signal and it should be fired before the process instance is completed - marked as completed so it still should have active context when executing CESP. The only issue I can see with it is that CESP should not have any wait states as then it will cause the process instance to complete and terminate the CESP.

P.S.
Is this ready to be merged? I mean you mentioned something about failing tests. Shall I look into them before pushing to master?

**Comment by mswiderski** [comment]
merged locally and fixed tests so now all is green :)

**Pull request closed without merging**
